
server:
  port: 8080
  servlet-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nbms?useUnicode=true&amp;characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: root
    password: 123456

mybatis:
 config-location: mybatis-config.xml
 
